spring.application.name: "externalRestDemo"


jwt:
  secret: ${JWT_SECRET}

spring:
  r2dbc:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
    pool:
      initial-size: 10
      max-size: 24
      max-idle-time: 30000ms

logging:
  level:
    org.springframework.r2dbc.core: debug
